# .gormgen.yaml

connection:
  driver: mysql
  dsn: root:123456@tcp(127.0.0.1:3306)/test?charset=utf8mb4&parseTime=True&loc=Local
  database: test

output:
  model: ./models
  repository: ./repositories
  service: ./services
